export type User = {
    uuid: string,
    userid: number,
    first_name: string,
    last_name: string,
    business_name: string,
    dob: string,
    phone: string,
    profilepic: string,
    username: string,
    bvn: string,
    nin: string,
    email: string,
    address: string,
    sex: string,
    referral: string,
    valid_id: string,
    signature: string,
    accountno: string,
    balance: string,
    currency: string,
    fixeddeposit: [],
    Creditbalance: number,
    Debitbalance: number
  }